kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-monkey-deployment
  namespace: monkey
  labels:
    app: go-monkey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-monkey
  template:
    metadata:
      labels:
        app: go-monkey
    spec:
      containers:
      - name: go-monkey
        image: replaceme
        command: ["/bin/bash", "-c"]
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1500m
            memory: 3000Mi
        args: ["./monkey-server -host=0.0.0.0 -port=5555 -logtostderr"]
        ports:
          - containerPort: 5555
        imagePullPolicy: "Always"
        env:
          - name: MONKEY_SEED
            valueFrom:
              secretKeyRef:
                name: monkey
                key: seed
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "14"                         
      imagePullSecrets:
          - name: regcred
 
